// Shared helpers for the custom Style Dictionary formats in this repo.
// Not published, not part of the library build — only used at token-generation time.

export function isToken(node) {
  return node !== null && typeof node === 'object' && !Array.isArray(node) && 'value' in node;
}

// Walks a Style Dictionary token subtree, replacing each leaf token with
// `mapLeaf(token)` while preserving the original nesting/group structure.
export function walk(node, mapLeaf) {
  if (isToken(node)) {
    return mapLeaf(node);
  }
  if (node !== null && typeof node === 'object') {
    const out = {};
    for (const [key, child] of Object.entries(node)) {
      out[key] = walk(child, mapLeaf);
    }
    return out;
  }
  return node;
}

function toCamelSegment(str) {
  return str
    .split(/[-_]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

// Mechanically derives a camelCase identifier from a token path, e.g.
// ['typography', 'body', 'small', 'semibold'] -> 'bodySmallSemibold'
// (the leading 'typography' segment is expected to be stripped by the caller).
export function pathToCamel(pathSegments) {
  return pathSegments
    .map(toCamelSegment)
    .map((seg, i) => (i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1)))
    .join('');
}

// Serializes a plain JS value (after walk()) into TypeScript source.
// All object keys are single-quoted so arbitrary token names ("2xl", "on-primary") are always valid.
export function serialize(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);

  if (value === null || value === undefined) return 'null';

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map(v => `${padIn}${serialize(v, indent + 1)}`).join(',\n');
    return `[\n${items},\n${pad}]`;
  }

  if (typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    const lines = keys.map(k => `${padIn}'${k}': ${serialize(value[k], indent + 1)}`).join(',\n');
    return `{\n${lines},\n${pad}}`;
  }

  if (typeof value === 'string') return JSON.stringify(value);

  return String(value);
}

export const LETTER_SPACING_CAVEAT =
  'letterSpacing is passed through exactly as exported from Figma (see tokens/figma-export.json _meta). ' +
  'Confirm whether it represents px or a percentage of font size before relying on it for layout-critical text.';

export function fileHeader(extraLines = []) {
  return [
    '/**',
    ' * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.',
    ' *',
    ' * Generated by Style Dictionary from tokens/figma-export.json.',
    ' * Regenerate with: npm run tokens:build',
    ' *',
    ` * NOTE: ${LETTER_SPACING_CAVEAT}`,
    ...extraLines.map(l => ` * ${l}`),
    ' */',
    '',
  ].join('\n');
}
