// Shared helpers for the custom Style Dictionary formats in this repo.
// Not published, not part of the library build — only used at token-generation time.

function toCamelSegment(str) {
  return str
    .split(/[-_]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

// Mechanically derives a camelCase identifier from a token path, e.g.
// ['typography', 'body', 'small', 'semibold'] -> 'bodySmallSemibold'
// (the leading 'typography' segment is expected to be stripped by the caller).
export function pathToCamel(pathSegments) {
  return pathSegments
    .map(toCamelSegment)
    .map((seg, i) => (i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1)))
    .join('');
}

// Serializes a plain JS value into TypeScript source.
// All object keys are single-quoted so arbitrary token names ("2xl", "on-primary") are always valid.
export function serialize(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);

  if (value === null || value === undefined) return 'null';

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map(v => `${padIn}${serialize(v, indent + 1)}`).join(',\n');
    return `[\n${items},\n${pad}]`;
  }

  if (typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    const lines = keys.map(k => `${padIn}'${k}': ${serialize(value[k], indent + 1)}`).join(',\n');
    return `{\n${lines},\n${pad}}`;
  }

  if (typeof value === 'string') return JSON.stringify(value);

  return String(value);
}

export function fileHeader(extraLines = []) {
  return [
    '/**',
    ' * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.',
    ' *',
    ' * Generated by Style Dictionary from tokens/figma-export.json.',
    ' * Regenerate with: npm run tokens:build',
    ' *',
    ...extraLines.map(l => ` * ${l}`),
    ' */',
    '',
  ].join('\n');
}
